AWSTemplateFormatVersion: 2010-09-09
Description: Creates DevOps / jump box
Parameters:
  PublicSubnet1ID:
    Description: Public Subnet Id 1
    Type: 'AWS::EC2::Subnet::Id'
  KeyPairName:
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Name of an existing EC2 KeyPair.
  SecGroup:
    Description: "Security Group ID."
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
  InstanceType:
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
    ConstraintDescription: "must be a valid EC2 instance type."
    Default: t3.medium
    Description: "EC2 instance type"
    Type: String
  VolumeSize:
    Type: Number
    Description: "EBS volume size of the DevOps Instance in GB"
    Default: 16
Mappings:
  AWSAMIRegionMapDevOps:
    ap-northeast-1:
      DevOps: ami-0aa261691d6ea2a33
    ap-northeast-2:
      DevOps: ami-0fddf3d9ac8338006
    ap-south-1:
      DevOps: ami-0833bbf36194139d9
    ap-southeast-1:
      DevOps: ami-0adc94c77b8b96882
    ap-southeast-2:
      DevOps: ami-067df23b9a35c666a
    ca-central-1:
      DevOps: ami-0cf8b858658304976
    eu-central-1:
      DevOps: ami-071eb55e4d03b55c4
    eu-north-1:
      DevOps: ami-0f430b432d6db27cd
    eu-west-1:
      DevOps: ami-07fad6b5b9599d8a3
    eu-west-2:
      DevOps: ami-0382a2829d036f2f3
    eu-west-3:
      DevOps: ami-03e3ccad6a8c2184a
    sa-east-1:
      DevOps: ami-043b177ff7006c52c
    us-east-1:
      DevOps: ami-0ad803069914859d7
    us-east-2:
      DevOps: ami-02985814fc7182bdb
    us-west-1:
      DevOps: ami-0806a6d260819379b
    us-west-2:
      DevOps: ami-046131ed9fc58b70f
Resources:
  DevNode1:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      # IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - DeleteOnTermination: true
          DeviceIndex: '0'
          SubnetId: !Ref PublicSubnet1ID
          GroupSet: !Ref SecGroup
      KeyName: !Ref KeyPairName
      ImageId: !FindInMap
        - AWSAMIRegionMapDevOps
        - !Ref 'AWS::Region'
        - DevOps
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: !Ref VolumeSize
            VolumeType: gp2
      Tags:
          - Key: Name
            Value: DevOps
Outputs:
  DevIpAddress:
    Value: !GetAtt DevNode1.PublicIp
    Description: Dev Jump box Public IP
  DevUrl:
    Value: "http://oss-getting-started.s3-website-us-east-1.amazonaws.com"
    Description: Dev Url
